// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZm8uGTHkp9kZ7U7l7l5lXbSemMlC9UiM',
    appId: '1:509283368235:web:395a06117b97fff3e8996e',
    messagingSenderId: '509283368235',
    projectId: 'docdoc-dc240',
    authDomain: 'docdoc-dc240.firebaseapp.com',
    storageBucket: 'docdoc-dc240.appspot.com',
    measurementId: 'G-MCYRR8GD5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjXgJu4DPpKecRaGU_ycJ3rVzSZp9HaXM',
    appId: '1:509283368235:android:71618ab140cac07de8996e',
    messagingSenderId: '509283368235',
    projectId: 'docdoc-dc240',
    storageBucket: 'docdoc-dc240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk6PKe5EnUZCnpHtn50supGfFUC6zE9Z0',
    appId: '1:509283368235:ios:59845954a89df726e8996e',
    messagingSenderId: '509283368235',
    projectId: 'docdoc-dc240',
    storageBucket: 'docdoc-dc240.appspot.com',
    iosBundleId: 'com.example.docdoc',
  );

}